org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
neo_version_range=[21,)
loader_version_range=[1,)

mod_id=complicated_bees
mod_name=Complicated Bees
mod_license=MIT
mod_version=3.6.2
mod_group_id=com.accbdd.complicated_bees
mod_authors=ACCBDD
mod_description=A data-driven implementation of diploid bees for modern versions of minecraft

# compat
jei_version = 19.27.0.340
jade_id = 7545219
emi_version = 1.1.22+1.21.1
rei_version = 16.0.799

# runtime testing
appleskin_id = 7854442
patchouli_id = 7730942
runtime_recipe_viewer = emi

# modded biome testing
bop_id = 7251965
glitchcore_id = 5660740
terrablender_id = 6054947
terralith_id = 6090387
bwg_id = 8245253

# bop, tl, bwg, none
runtime_biome_test = bwg